//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tartIsh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminTask
    {
        public int Id { get; set; }
        public string Task { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<int> Progress { get; set; }
    
        public virtual TartIshUser TartIshUser { get; set; }
    }
}
