//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tartIsh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedMessage
    {
        public int Id { get; set; }
        public int SenderId { get; set; }
        public int ReceiverId { get; set; }
        public string MessageText { get; set; }
        public System.DateTime SentDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual TartIshUser TartIshUser { get; set; }
        public virtual TartIshUser TartIshUser1 { get; set; }
    }
}
