//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tartIsh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mastery
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CategoryWins { get; set; }
        public int CategoryMatchingCount { get; set; }
        public Nullable<System.DateTime> LastMatch { get; set; }
        public Nullable<System.DateTime> LastOwnedDate { get; set; }
        public double Rates { get; set; }
        public Nullable<bool> IsPassive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual TartIshUser TartIshUser { get; set; }
    }
}
