//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tartIsh.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tartIshEntities : DbContext
    {
        public tartIshEntities()
            : base("name=tartIshEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTask> AdminTasks { get; set; }
        public virtual DbSet<BanType> BanTypes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<DeletedMessage> DeletedMessages { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Hobby> Hobbies { get; set; }
        public virtual DbSet<Mastery> Masteries { get; set; }
        public virtual DbSet<NotificationUser> NotificationUsers { get; set; }
        public virtual DbSet<PersonComplaint> PersonComplaints { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
        public virtual DbSet<PollOption> PollOptions { get; set; }
        public virtual DbSet<Premium> Premiums { get; set; }
        public virtual DbSet<PremiumUser> PremiumUsers { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<RoomComplaint> RoomComplaints { get; set; }
        public virtual DbSet<RoomVote> RoomVotes { get; set; }
        public virtual DbSet<RoomVote1> RoomVotes1 { get; set; }
        public virtual DbSet<Rosette> Rosettes { get; set; }
        public virtual DbSet<Suggestion> Suggestions { get; set; }
        public virtual DbSet<TartIshRoom> TartIshRooms { get; set; }
        public virtual DbSet<TartIshSection> TartIshSections { get; set; }
        public virtual DbSet<TartIshStatu> TartIshStatus { get; set; }
        public virtual DbSet<TartIshUser> TartIshUsers { get; set; }
        public virtual DbSet<UserBan> UserBans { get; set; }
        public virtual DbSet<UserHoby> UserHobies { get; set; }
        public virtual DbSet<UserMessage> UserMessages { get; set; }
        public virtual DbSet<UserRosette> UserRosettes { get; set; }
        public virtual DbSet<UserSelectedPoll> UserSelectedPolls { get; set; }
        public virtual DbSet<UserStatu> UserStatus { get; set; }
        public virtual DbSet<UserSubscriber> UserSubscribers { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<UserWatchedRoom> UserWatchedRooms { get; set; }
    }
}
