//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tartIsh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int SenderId { get; set; }
        public int ReceiverId { get; set; }
        public double RatingValue { get; set; }
        public string Reason { get; set; }
        public bool IsPassive { get; set; }
    
        public virtual TartIshUser TartIshUser { get; set; }
        public virtual TartIshUser TartIshUser1 { get; set; }
        public virtual TartIshUser TartIshUser2 { get; set; }
        public virtual TartIshUser TartIshUser3 { get; set; }
    }
}
