//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tartIsh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TartIshRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TartIshRoom()
        {
            this.Documents = new HashSet<Document>();
            this.Polls = new HashSet<Poll>();
            this.RoomComplaints = new HashSet<RoomComplaint>();
            this.RoomVotes = new HashSet<RoomVote1>();
            this.UserStatus = new HashSet<UserStatu>();
            this.UserWatchedRooms = new HashSet<UserWatchedRoom>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string RoomDescription { get; set; }
        public int CategoryId { get; set; }
        public int ViewersCount { get; set; }
        public int RoomCreatorId { get; set; }
        public Nullable<int> RivalId { get; set; }
        public string RoomImageUrl { get; set; }
        public Nullable<int> ChatId { get; set; }
        public System.DateTime RoomStartDate { get; set; }
        public Nullable<System.DateTime> RoomFinishDate { get; set; }
        public Nullable<int> WinnerId { get; set; }
        public bool IsRoomPrivate { get; set; }
        public Nullable<bool> IsRunAway { get; set; }
        public Nullable<bool> IsPassive { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public Nullable<int> RunawayId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Chat Chat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poll> Polls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomComplaint> RoomComplaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomVote1> RoomVotes { get; set; }
        public virtual TartIshUser TartIshUser { get; set; }
        public virtual TartIshUser TartIshUser1 { get; set; }
        public virtual TartIshUser TartIshUser2 { get; set; }
        public virtual TartIshUser TartIshUser3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserStatu> UserStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserWatchedRoom> UserWatchedRooms { get; set; }
    }
}
