//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tartIsh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TartIshSection
    {
        public int Id { get; set; }
        public string SectionName { get; set; }
        public string Title { get; set; }
        public int ViewerTypeId { get; set; }
        public string Content { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
