//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tartIsh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRosette
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int RosetteId { get; set; }
        public System.DateTime OwnedDate { get; set; }
        public bool IsPassive { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Rosette Rosette { get; set; }
        public virtual TartIshUser TartIshUser { get; set; }
        public virtual TartIshUser TartIshUser1 { get; set; }
    }
}
